-- Comments in SQL Start with dash-dash --
-- Question 1
-- INSERT INTO products (name, price, can_be_returned) VALUES ('chair', '44.00', false)
-- Question 2
-- INSERT INTO products (name, price, can_be_returned) VALUES ('chair', '44.00', false);
-- Question 3
-- INSERT INTO products (name, price, can_be_returned) VALUES ('table', 124.00, false);
-- Question 4
-- SELECT * FROM products;
-- Question 5
-- SELECT name FROM products;
-- Question 6
-- SELECT name,price FROM products;
-- Question 7
-- INSERT INTO products (name, price, can_be_returned) VALUES ('guitar', 800.90, false);
-- Question 8
-- SELECT name FROM products WHERE can_be_returned = 't';
-- Question 9
-- SELECT name FROM products WHERE price < 44.00;
-- Question 10
-- SELECT name FROM products WHERE price BETWEEN 22.50 and 99.99;
-- Question 11
-- UPDATE products SET price = price-20;
-- Question 12
-- DELETE FROM products WHERE price < 25;
-- Question 13
-- UPDATE products SET price = price+20;
-- Question 14
-- UPDATE products SET can_be_returned = 't';


